blog/urls.py
from django.urls import path, include, re_path
from app001 import views
from django.views.static import serve
from django.conf import settings
from app001 import urls as blog_urls
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('reg/', views.reg),
    path('index/', views.index),
    path('login/', views.login),
    path('logout/', views.logout),
    path('upload/', views.upload),
    # 交给app0001的url 处理
    re_path(r'^blog', include(blog_urls)),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),

]



app001/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class UserInfo(AbstractUser):
    """
    用户信息表
    """
    nid = models.AutoField(primary_key=True)
    phone = models.CharField(max_length=11, null=True, unique=True, blank=True)
    avatar = models.FileField(upload_to="avatars/", default="avatars/default.png", verbose_name="头像")
    create_time = models.DateTimeField(auto_now_add=True)
    blog = models.OneToOneField(to="Blog", to_field="nid", null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = "用户"
        verbose_name_plural = verbose_name


class Blog(models.Model):
    """
    博客信息
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=64)  # 个人博客标题
    site = models.CharField(max_length=32, unique=True)  # 个人博客后缀
    theme = models.CharField(max_length=32)  # 博客主题

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "blog站点"
        verbose_name_plural = verbose_name


class Category(models.Model):
    """
    个人博客文章分类
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=32)  # 分类标题
    blog = models.ForeignKey(to="Blog", to_field="nid", on_delete=models.CASCADE)  # 外键关联博客，一个博客站点可以有多个分类

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "文章分类"
        verbose_name_plural = verbose_name


class Tag(models.Model):
    """
    标签
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=32)  # 标签名
    blog = models.ForeignKey(to="Blog", to_field="nid", on_delete=models.CASCADE)  # 所属博客

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "标签"
        verbose_name_plural = verbose_name


class Article(models.Model):
    """
    文章
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50, verbose_name="文章标题")  # 文章标题
    desc = models.CharField(max_length=255)  # 文章描述
    create_time = models.DateTimeField(auto_now_add=True)  # 创建时间
    # 评论数
    comment_count = models.PositiveIntegerField(verbose_name="评论数", default=0)
    # 点赞数
    up_count = models.PositiveIntegerField(verbose_name="点赞数", default=0)
    # 踩
    down_count = models.PositiveIntegerField(verbose_name="踩数", default=0)
    category = models.ForeignKey(to="Category", to_field="nid", null=True, on_delete=models.CASCADE)
    user = models.ForeignKey(to="UserInfo", to_field="nid", on_delete=models.CASCADE)
    tags = models.ManyToManyField(  # 中介模型
        to="Tag",
        through="Article2Tag",
        through_fields=("article", "tag"),  # 注意顺序！！！
    )

    def __str__(self):
        """返回模型的字符串表示"""
        small_text = self.desc[:50]
        if small_text == self.desc:
            return self.desc
        else:
            return self.desc[:50] + "..."

    class Meta:
        verbose_name = "文章"
        verbose_name_plural = verbose_name


class ArticleDetail(models.Model):
    """
    文章详情表
    """
    nid = models.AutoField(primary_key=True)
    content = models.TextField(verbose_name="文章具体内容")
    article = models.OneToOneField(to="Article", to_field="nid", verbose_name="关联的文章标题", on_delete=models.CASCADE)

    def __str__(self):
        return self.content[:280]

    class Meta:
        verbose_name = "文章详情"
        verbose_name_plural = verbose_name


class Article2Tag(models.Model):
    """
    文章和标签的多对多关系表
    """
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(to="Article", to_field="nid", on_delete=models.CASCADE)
    tag = models.ForeignKey(to="Tag", to_field="nid", on_delete=models.CASCADE)

    def __str__(self):
        # return "{}-{}".format(self.article.title, self.tag.title)
        return self.article.title[:20] + "---" + self.tag.title
        # 我贼尼玛 老子死也没想出阿来，怎么拼接

    class Meta:
        unique_together = (("article", "tag"),)
        verbose_name = "文章-标签"
        verbose_name_plural = verbose_name


class ArticleUpDown(models.Model):
    """
    点赞表
    """
    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey(to="UserInfo", null=True, on_delete=models.CASCADE)
    article = models.ForeignKey(to="Article", null=True, on_delete=models.CASCADE)
    is_up = models.BooleanField(default=True)

    class Meta:
        unique_together = (("article", "user"),)
        verbose_name = "文章点赞"
        verbose_name_plural = verbose_name


class Comment(models.Model):
    """
    评论表
    """
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(to="Article", to_field="nid", on_delete=models.CASCADE)
    user = models.ForeignKey(to="UserInfo", to_field="nid", on_delete=models.CASCADE)
    content = models.CharField(max_length=255)  # 评论内容
    create_time = models.DateTimeField(auto_now_add=True)
    parent_comment = models.ForeignKey("self", null=True, blank=True, on_delete=models.CASCADE)
    # blank=True 在django admin里面可以不填

    def __str__(self):
        return self.content

    class Meta:
        verbose_name = "评论"
        verbose_name_plural = verbose_name

templates/add_article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/boot1/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/mystyle.css">
    <link rel="stylesheet" href="/static/theme/{{ blog.theme }}.css">
    <style>
        * {
            margin: 0;
        }
        .header {
            width: 100%;
            height: 60px;
            background-color: #369;
        }

        .content {
            width: 70%;
            margin: 20px auto;
        }

    </style>
</head>
<body>
    <div class="header"></div>
    <div class="content">
        <h3>添加文章</h3>
        <form action="" method="post">
        {% csrf_token %}
            <div>
            <label for="">文章标题</label>
            <input type="text" name="title" class="form-control" style="width: 300px">
        </div>
            <div>
            <p>内容</p>
            <textarea name="article_content" id="article_content" cols="70" rows="20"></textarea>
        </div>
        <input type="submit" value="提交" class="btn btn-success">
        </form>
    </div>
<script src="/static/jquery-3.3.1.js"></script>
<script src="/static/boot1/js/bootstrap.min.js"></script>
<script charset="utf-8" src="/static/kindeditor/kindeditor-all-min.js"></script>
<script>
        KindEditor.ready(function(K) {
                window.editor = K.create('#article_content', {
                    width: "700",
                    uploadJson:"/upload/",
                    //传数据要用这参数
                    extraFileUploadParams:{
                        csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val(),
                    },
                    //默认是叫 imgFIle, 指定名称
                    filePostName:"upload_img"
                });

        });
</script>
</body>
</html>

templates/article_detail.html
{% extends 'base.html' %}
{% block page-main %}
    <script src="/static/jquery-3.3.1.js"></script>
    <div class="article title">
        <h1>{{ article.title }}</h1>
        <p>{{ article.articledetail.content|safe }} </p>
    </div>
      <div class="poll clearfix">                 {# 清除浮动  不在一行#}
        <div id="div_digg">
        <div class="diggit action">
            <span class="diggnum" id="digg_count">{{ article.up_count }}</span>
        </div>
        <div class="buryit action">
            <span class="burynum" id="bury_count">{{ article.down_count }}</span>
        </div>
        <div class="clear"></div>
        <div class="diggword" id="digg_tips" style="color: red"></div>
    </div>
    </div>
{#    // 评论树#}
{#    <p>评论树</p>#}
{#    <div class="comment_tree">#}
{#    </div>#}

    <hr>
    <h3>评论列表：</h3>
    <ul class="comment_list">
    {% for comment in comment_list %}
        <li class="list-group-item">
            <div>
                <a href="">#{{ forloop.counter }}楼</a> &nbsp; &nbsp;
                <span style="color: gray">{{ comment.create_time|date:"Y-m-d H:i" }}</span>
                <a href=""><span>{{ comment.user.username }}</span></a>
                <a class="pull-right reply-btn" username="{{ comment.user.username }}" comment_pk="{{ comment.pk }}"><span>回复</span></a>
            </div>
            {% if comment.parent_comment_id %}
                <div class="pid_info well">
                    {{ comment.parent_comment.user.username }} &nbsp;&nbsp;&nbsp;{{ comment.parent_comment.content }}
                </div>
            {% endif %}

            <div class="con">
                <p>
                    {{ comment.content }}
                </p>
            </div>
    </li>
    {% endfor %}
    </ul>
    {% if request.user.username%}
        <div class="div_comment">
        <p>昵称：<input type="text" id="tbCommentAuthor" class="author" disabled="disabled" size="50" value="{{ request.user.username }}"></p>
        <p>评论内容：</p>
        <textarea  id="comment_content" cols="60" rows="9"></textarea>
        <p><button id="comment_btn">提交评论</button></p>
        </div>
    {% else %}
        <a href="/login/">请登录</a>
    {% endif %}

    <script>

        {#//  评论树#}
        {#$.ajax({#}
        {#    url: "/blog/comment_tree/" + '{{ article.pk }}/',#}
        {#    success:function(data) {#}
        {#        $.each(data, function (index, comment_dict) {#}
        {#            let s= '<div class="comment_item" comment_id='+ comment_dict.pk +' ><span class="content">'+ comment_dict.content+'</span></div>';#}
        {#            if (comment_dict.parent_comment_id){#}
        {#                // 子评论#}
        {#                pid=comment_dict.parent_comment_id;#}
        {#                $("[comment_id=" + pid+ "]").append(s);#}
        {#            }else{#}
        {#                // 根评论#}
        {#                $(".comment_tree").append(s);#}
        {#            }#}
        {##}
        {#        })#}
        {#    }#}
        {# }); #}





        let pid="";
        $("#comment_btn").on("click",function () {
            let article_id="{{ article.nid }}";
            let content=$("#comment_content").val();
            if (pid){
                let index=content.indexOf("\n");
                content=content.slice(index+1);
            }

            $.ajax({
                url:"/blog/comment/",
                type: "post",
                data:{
                    article_id:article_id,
                    content:content,
                    pid:pid,
                    csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val(),
                },
                success:function (data) {
                     let create_time=data.create_time;
                     let content=data.content;
                     let username=data.username;


                    let comment_li='<li class="list-group-item">\n' +
                        '        <div>\n' +
                        '            <span style="color: gray">'+create_time+'</span>\n' +
                        '            <a href=""><span>'+username+'</span></a>\n' +
                        '        </div>\n' +
                        '        <div class="con">\n' +
                        '            <p>'+content+'</p>\n' +
                        '        </div>\n' +
                        '    </li>';
                        $(".comment_list").append(comment_li);
                        $("#comment_content").val("");
                        pid="";
                }
                }
            )
        });


        //回复按钮事件
        $(".list-group-item .reply-btn").click(function () {
            $("#comment_content").focus();
            let v="@"+$(this).attr("username")+"\n";
            $("#comment_content").val(v);
            pid=$(this).attr("comment_pk")
        })
    </script>

    {% csrf_token %}
    <script>
        $("#div_digg .action").on("click", function () {
            if ("{{ request.user.username }}"){
                let is_up=$(this).hasClass("diggit");
                let article_id="{{ article.pk }}";
                $.ajax({
                url:"/blog/up_down/",
                type:"post",
                data:{
                    csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val(),
                    is_up:is_up,
                    article_id:article_id,
                },
                success:function (data) {
                   if (data.state){
                       if(is_up){
                           let val=$("#digg_count").text();

                           val=parseInt(val)+1;
                           $("#digg_count").text(val);
                       }else{
                           let val=$("#bury_count").text();
                           val=parseInt(val)+1;
                           $("#bury_count").text(val);
                       }
                   }
                   else{
                       if (data.first_action){
                          $("#digg_tips").html("您已经推荐过");
                       }else{
                           $("#digg_tips").html("您已经反对过");
                       }
                       setTimeout(function () {
                           $("#digg_tips").html("")
                       }, 1000)

                   }
                }
            })
            }else{
                location.href="/login/"
            }

        })
    </script>
    
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ username }}的个人博客</title>
    <link rel="stylesheet" href="/static/boot1/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/mystyle.css">
    <link rel="stylesheet" href="/static/theme/{{ blog.theme }}.css">

</head>
<body>
<div class="header">
    <p>{{ blog.title }} の博客</p>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-3">
                {% load mytags %}

                {% get_left_menu username %}
        </div>

        <div class="col-md-8">
            {% block page-main %}

            {% endblock %}

        </div>
    </div>
</div>
<script src="/static/jquery-3.3.1.js"></script>
<script src="/static/boot1/js/bootstrap.min.js"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block page-main %}
    <div class="article-list">
                {% for article in article_list %}
                    <div class="article">
                        <p class="article-title"><a href="/blog/{{ article.user.username }}/article/{{ article.pk }}/">{{ article.title }}</a></p>
                        <div class="media">
                            <div class="media-left">
                                <a href="/blog/{{ article.user.username }}">
                                    <img class="media-object" src="/media/{{ article.user.avatar }}"
                                         alt="失敗した" height="60px" width="60px">
                                </a>
                            </div>
                            <div class="media-body">
                                <h4 class="media-heading">{% if article.desc|length < 180 %}
                                        {{ article.desc }}
                                    {% else %}
                                        {{ article.desc|truncatechars:180 }}
                                    {% endif %}
                                </h4>
                            </div>
                        </div>
                        <div class="article-footer">
                            <span><a href="/blog/{{ article.user.username }}/">{{ article.user.username }}</a></span>发布于
                            <span>{{ article.create_time|date:'Y-m-d H:i:s' }}</span>
                            <span class="glyphicon glyphicon-comment">评论({{ article.comment_count }})</span>
                            <span class="glyphicon glyphicon-thumbs-up" style="margin-bottom: 50px">点赞({{ article.up_count }})</span>
                        </div>
                    </div>
                {% endfor %}

            </div>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>主页</title>
    <link rel="stylesheet" href="/static/boot1/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/mystyle.css">
</head>

<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">The Blog</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
                <li><a href="#">Link</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.username %}
                    <li><a href="#">{{ request.user.username }}</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">个人中心<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="/logout/">注销</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="/login/">登录</a></li>
                    <li><a href="/reg/">注册</a></li>
                {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<!-- 主页面 开始-->
<div class="container">
    <div class="row">
        <div class="col-md-2">
            <div class="panel panel-primary">
                <div class="panel-heading">左侧广告位一</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
            <div class="panel panel-info">
                <div class="panel-heading">左侧广告位二</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <!-- 文章列表 开始 -->
            <div class="article-list">
                {% for article in article_list %}
                    <div class="article">
                        <p class="article-title"><a href="/blog/{{ article.user.username }}/article/{{ article.pk }}/">{{ article.title }}</a></p>
                        <div class="media">
                            <div class="media-left">
                                <a href="/blog/{{ article.user.username }}">
                                    <img class="media-object" src="/media/{{ article.user.avatar }}"
                                         alt="失敗した" height="60px" width="60px">
                                </a>
                            </div>
                            <div class="media-body">
                                <h4 class="media-heading">
                                    {% if article.desc|length < 150 %}
                                        {{ article.desc|safe }}
                                    {% else %}
                                        {{ article.desc|truncatechars:150 }}
                                    {% endif %}
                                </h4>
                            </div>
                        </div>
                        <div class="article-footer">
                            <span><a href="/blog/{{ article.user.username }}/">{{ article.user.username }}</a></span>发布于
                            <span>{{ article.create_time|date:'Y-m-d H:i:s' }}</span>
                            <span class="glyphicon glyphicon-comment">评论({{ article.comment_count }})</span>
                            <span class="glyphicon glyphicon-thumbs-up"
                                  style="margin-bottom: 50px">点赞({{ article.up_count }})</span>
                        </div>
                    </div>
                {% endfor %}

            </div>
<!--                       文章列表 结束                                          -->

        </div>
        <div class="col-md-2">
            <div class="panel panel-primary">
                <div class="panel-heading">右侧广告位一</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
            <div class="panel panel-info">
                <div class="panel-heading">右侧广告位二</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
        </div>
    </div>
</div>


<!--                  主面板结束                    -->

<script src="/static/jquery-3.3.1.js"></script>
<script src="/static/boot1/js/bootstrap.min.js"></script>
</body>
</html>

templates/left_menu.html
<div class="panel panel-primary">
    <div class="panel-heading">文章分类</div>
    <div class="panel-body">
        {% for category in category_list %}
            <p>{{ category.title }} ({{ category.article_set.all.count }})</p>
        {% endfor %}
    </div>
</div>

<div class="panel panel-info">
    <div class="panel-heading">标签分类</div>
    <div class="panel-body">
        {% for tag in tag_list %}
            <p>{{ tag.title }} ({{ tag.article_set.count }}) </p>
        {% endfor %}

    </div>
</div>
<div class="panel panel-danger">
    <div class="panel-heading">时间分类</div>
    <div class="panel-body">
        {% for archive in archive_list %}
            <p>{{ archive.archive_ym }} ({{ archive.c }}) </p>
        {% endfor %}

    </div>
</div>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/boot1/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/mystyle.css">
</head>
<body>
    <div class="container">
    <div class="row">
        <form class="form-horizontal col-md-8 col-md-offset-3 login-form log-form"
              action="/login/" method="post" autocomplete="off">
            {% csrf_token %}
            <div class="col-md-offset-4" ><h1 style="color: #ec971f">登陆</h1></div>
            <div class="form-group">
                <label for="username" class="col-sm-2 control-label">用户名</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control" id="username" name="username" placeholder="用户名">
                     <span id="helpBlock2" class="help-block">{{ msg.username }}</span>
                </div>
            </div>
            <div class="form-group">
                <label for="password" class="col-sm-2 control-label">密码</label>
                <div class="col-sm-6">
                    <input type="password" class="form-control" id="password" name="password" placeholder="密码">
                     <span id="helpBlock2" class="help-block">{{ msg.password }}</span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="button" class="btn btn-success" id="login-button">登录</button>
                    <span class="login-error"></span>
                </div>
            </div>
        </form>
    </div>
</div>
<script src="/static/jquery-3.3.1.js"></script>
<script src="/static/boot1/js/bootstrap.min.js"></script>
<script>
    $("#login-button").on("click", function () {
        let username = $("#username").val();
        let password = $("#password").val();

        $.ajax({
            url: "/login/",
            type: "post",
            data: {
                username: username,
                password: password,
                csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val(),
            },
            success:function (data) {
                if (data.username){
                    $("#username").next("span").text(data.username).parent().parent().addClass("has-error");
                }else{
                    if (data.password){
                        $("#password").next("span").text(data.password).parent().parent().addClass("has-error");
                    }else{
                          location.href = "/index/";
                    }
                }
            }
        });
        
        $("form input").on("focus", function () {
            $(this).next().text("").parent().parent().removeClass("has-error")
        })
    });
</script>
</body>
</html>

templates/reg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册页面</title>
    <link rel="stylesheet" href="/static/boot1/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/mystyle.css">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-3">
            <form novalidate autocomplete="off" action="/reg/" class="form-horizontal reg-form" enctype="multipart/form-data"
                  method="post">
                {% csrf_token %}
                <div class="col-md-offset-4"> <h1 style="color: #ec971f">注册</h1></div>
                <!--             用户名                -->
                <div class="form-group {% if form_obj.username.errors.0 %} has-error {% endif %}">
                    <label for="{{ form_obj.username.id_for_label }}"
                           class="col-sm-2 control-label">{{ form_obj.username.label }}</label>
                    <div class="col-sm-6">
                        {{ form_obj.username }}
                        <span id="helpBlock2" class="help-block">{{ form_obj.username.errors.0 }}</span>
                    </div>
                </div>

                <div class="form-group {% if form_obj.password.errors.0 %} has-error {% endif %}">
                    <label for="{{ form_obj.password.id_for_label }}"
                           class="col-sm-2 control-label">{{ form_obj.password.label }}</label>
                    <div class="col-sm-6">
                        {{ form_obj.password }}
                        <span id="helpBlock2" class="help-block">{{ form_obj.password.errors.0 }}</span>
                    </div>
                </div>

                <div class="form-group {% if form_obj.re_password.errors.0 %} has-error {% endif %}">
                    <label for="{{ form_obj.re_password.id_for_label }}"
                           class="col-sm-2 control-label">{{ form_obj.re_password.label }}</label>
                    <div class="col-sm-6">
                        {{ form_obj.re_password }}
                        <span id="helpBlock2" class="help-block">{{ form_obj.re_password.errors.0 }}</span>
                    </div>
                </div>

                <div class="form-group {% if form_obj.email.errors.0 %} has-error {% endif %}">
                    <label for="{{ form_obj.email.id_for_label }}"
                           class="col-sm-2 control-label">{{ form_obj.email.label }}</label>
                    <div class="col-sm-6">
                        {{ form_obj.email }}
                        <span id="helpBlock2" class="help-block">{{ form_obj.email.errors.0 }}</span>
                    </div>

                </div>
                <div class="form-group">
                    <label for="" class="col-sm-2 control-label">头像</label>
                    <div class="col-sm-6">
                        <label for="id_avatar"><img id="avatar-img" src="/static/default.png" alt="默认头像"></label>
                        <input accept="image/*" type="file" name="avatar" id="id_avatar" style="display: none">
                        <span id="helpBlock2" class="help-block"></span>
                    </div>
                </div>
                <button type="submit" class="btn btn-success tj" id="reg-submit">注册</button>
            </form>
            <script src="/static/jquery-3.3.1.js"></script>
            <script src="/static/boot1/js/bootstrap.min.js"></script>
            <script>
                 //找到头像框
                $("#id_avatar").on("change", function () {
                    let fileReader = new FileReader();
                    //读取文件对象
                    fileReader.readAsDataURL(this.files[0]);  //读文件需要时间
                    //读完文件之后才，加载图片
                    fileReader.onload = function () {
                        $("#avatar-img").attr("src", fileReader.result);
                    };
                });
            </script>
        </div>
    </div>
</div>

</body>
</html>